const quoteCards = [
  {
    id: 1,
    bg: '#F2E1D3',
    textColor: '#AA7D55',
    quote: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    author: '@sari.kusumaningrum',
    fontFamily: 'Courier Prime, monospace',
  },
  {
    id: 2,
    bg: '#F5EFE6',
    textColor: '#8B5E3C',
    quote: 'Vivamus non felis at orci commodo ullamcorper.',
    author: '@sari.kusumaningrum',
    fontFamily: 'Courier Prime, monospace',
  },
  {
    id: 3,
    bg: '#EDE3D2',
    textColor: '#C27D4A',
    quote: 'Simplicity is the ultimate sophistication.',
    author: '@sari.kusumaningrum',
    fontFamily: 'Courier Prime, monospace',
  },
  {
    id: 4,
    bg: '#F7ECD6',
    textColor: '#A56D34',
    quote: 'Kreasi tanpa batas, inspirasi tanpa akhir.',
    author: '@sari.kusumaningrum',
    fontFamily: 'Courier Prime, monospace',
  },
  {
    id: 5,
    bg: '#F0E4D7',
    textColor: '#9B6B4A',
    quote: 'Innovation drives progress and change.',
    author: '@sari.kusumaningrum',
    fontFamily: 'Courier Prime, monospace',
  },
  {
    id: 6,
    bg: '#F3E5D8',
    textColor: '#B87A4F',
    quote: 'Creativity is intelligence having fun.',
    author: '@sari.kusumaningrum',
    fontFamily: 'Courier Prime, monospace',
  },
  {
    id: 7,
    bg: '#E8D5C4',
    textColor: '#8F5B3A',
    quote: 'The best way to predict the future is to create it.',
    author: '@sari.kusumaningrum',
    fontFamily: 'Courier Prime, monospace',
  },
  {
    id: 8,
    bg: '#F6EBE0',
    textColor: '#A76F42',
    quote: 'Design is not just what it looks like and feels like. Design is how it works.',
    author: '@sari.kusumaningrum',
    fontFamily: 'Courier Prime, monospace',
  },
  {
    id: 9,
    bg: '#EFDCC9',
    textColor: '#C68B5E',
    quote: 'Art is not what you see, but what you make others see.',
    author: '@sari.kusumaningrum',
    fontFamily: 'Courier Prime, monospace',
  },
];

export default quoteCards;